C:37:"PHPUnit\Runner\DefaultTestResultCache":439:{a:2:{s:7:"defects";a:2:{s:7:"Warning";i:6;s:62:"ChainTest::it_throws_an_exception_when_a_class_does_not_exists";i:3;}s:5:"times";a:5:{s:7:"Warning";d:0.001;s:50:"ChainTest::it_returns_an_instance_of_chain_on_init";d:0;s:75:"ChainTest::it_accepts_method_calls_to_classes_that_exists_and_return_itself";d:0;s:42:"CategoryTest::it_returns_a_category_string";d:0.001;s:62:"ChainTest::it_throws_an_exception_when_a_class_does_not_exists";d:0;}}}